### ISSUE TITLE
Cannot make it work, getting error in 'continuation-local-storage'

### ISSUE THREAD

**Issue by ptpavankumar** [burkhartt/autonode#4]
Can you please help me on this? I really like your IoC and i cannot prove to my team that it works!

Usage:

app.js >
```
const ioc = require('./ioc');
....
....
app.use(ioc.Middleware);
app.use((req, res, next) => {
  req.scope = ioc.Container; 
  next();
});
```

ioc.js >>>

```
const autonode = require('auto-node');

const knex = require('knex');

const dbConfig = require('./config/dbconfig');
const TYPES = require('./models').types;
const repositories = require('./repository');

const containerBuilder = new autonode.ContainerBuilder();

const stack = process.env.STACK || 'development';
const knexInstance = knex(dbConfig[stack]);

// Register all the repositories
containerBuilder.registerType(TYPES.Address, repositories.AddressRepository, autonode.LifetimeScope.InstancePerRequest);
containerBuilder.registerType(TYPES.User, repositories.UserRepository, autonode.LifetimeScope.InstancePerRequest);
containerBuilder.register(TYPES.Knex, knexInstance, autonode.LifetimeScope.SingleInstance);

autonode.Container.load(containerBuilder);

module.exports = autonode;
```

**Error**:
```
/Users/XXXX/node_modules/continuation-local-storage/context.js:90
      throw exception;
      ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at Array.write (/Users/XXXX/node_modules/finalhandler/index.js:202:9)
    at listener (/Users/XXXX/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/XXXX/node_modules/on-finished/index.js:100:5)
    at callback (/Users/XXXX/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/Users/XXXX/node_modules/ee-first/index.js:93:5)
    at IncomingMessage.<anonymous> (/Users/XXXX/node_modules/continuation-local-storage/context.js:84:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at IncomingMessage.emitted [as emit] (/Users/XXXX/node_modules/emitter-listener/listener.js:122:21)
    at endReadableNT (_stream_readable.js:934:12)
    at /Users/XXXX/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.2.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! Service-template-with-Auto-node-as-IoC@0.0.1 dev: `babel-node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Service-template-with-Auto-node-as-IoC@0.0.1 dev script 'babel-node src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Service-template-with-Auto-node-as-IoC package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Service-template-with-Auto-node-as-IoC
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Service-template-with-Auto-node-as-IoC
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXX/npm-debug.log

```

**Comment by burkhartt** [comment]
Hi,

Unfortunately I can't recommend using this library (I REALLY wish that I could recommend it because I really liked it when I made it); however, it is based upon using the library continuation-local-storage, which is great, except that after making this, I watched a video of the creator of continuation-local-storage at a tech conference talk about that particular library and mention that it works in all scenarios *except* a few ... and one of those few was promises, which is pretty fundamental nowadays to JavaScript in general. Once I found out about that, I stopped working on this project. ... It's very disappointing, I know :( ... So I can't recommend continuing on with this library--it's in the best interest of your team, sadly.

I will update the readme accordingly.

-Tim
